### ISSUE TITLE
Outline effect not updating with mesh deformation.

### ISSUE THREAD

**Issue by ModarD** [alelievr/HDRP-Custom-Passes#27]
Hi,

I'm using a compute shader to deform the outlined mesh. but the outline is not updating with the mesh deformation. it just keeps the initial shape of the mesh before deformation. 

I also noticed that the default orange selection outline in the editor works correctly with mesh deformation.

Any idea what could be causing this issue?

Thank you!

**Comment by alelievr** [comment]
It's probably because of the override material that replaces your custom deformation shader, that's one of the shortcomings of the current outline in the repo.

One more clever way to handle that would be to render all the objects that need to be outlined with a custom stencil state (using de DrawRenderers API) and then use this stencil to do the outline. The problem then with this is that we loose the ability to have a different outline color per renderer.
