### ISSUE TITLE
Render from different camera to a texture/rendertexture

### ISSUE THREAD

**Issue by ArieLeo** [alelievr/HDRP-Custom-Passes#35]
Is it possible to from different camera and output the frame buffer to a texture/rendertexture with custom pass?
my use case is for minimap , a custom buffer for terrain deformation or water ripple.
any chance to get a small sample scene for this?
I guess it's similar to CopyPass sample but rendered from different camera?

**Comment by alelievr** [comment]
Yeah, it's possible with the RenderFrom functions in the CustomPassUtils class.
You can have a look at this file for implementation details: https://github.com/alelievr/HDRP-Custom-Passes/blob/master/Assets/Scenes/CameraDepthBaking/CameraDepthBake.cs#L45
(instead of render depth, or normal, you can render the color)
