### ISSUE TITLE
FPS Foreground Motion Vector and TAA

### ISSUE THREAD

**Issue by ArieLeo** [alelievr/HDRP-Custom-Passes#44]
The latest commit seems fixed the issue of Fps Foreground with transparency and post processing. But TAA and motion vector seems doesn't work 
Any clue/pointer on how to add support for TAA and motion vector to this?

**Comment by alelievr** [comment]
Yes, we can fix motion vectors by adding another pass that writes motion vectors of the FPS objects. But this is still not a perfect solution since you'll still have issues with shadows during lighting, subsurface scattering, and probably a few others.

**Comment by alelievr** [comment]
Hey, I added support for Motion vectors in the FPS custom pass (it removed motion from the FPS objects).

There is one issue though: it also removes a bit of motion on the border of the FPS objects because the motion blur can't reproject values that were cleared:
![image](https://github.com/alelievr/HDRP-Custom-Passes/assets/6877923/8a97e682-422d-4de7-8134-3792c2045401)

Also, it doesn't handle well SSAO currently, I can't nuke the depth buffer values like I was planning to do because it breaks the tile light list generation (and so the lighting of the object). That leads to the SSAO being applied to foreground objects when they are close to a surface:
![image](https://github.com/alelievr/HDRP-Custom-Passes/assets/6877923/c7a5e52d-814c-4a8d-9dd5-b3af1e2d0f02)


You can tweak the effect to reduce the visual impact of these issues though so it's not unusable. I can see a more complete solution being made inside HDRP and handled well by all the internal passes, but it's not the priority right now :/
