### ISSUE TITLE
SSAO leaks into FPS foreground

### ISSUE THREAD

**Issue by Mohammad9760** [alelievr/HDRP-Custom-Passes#52]
![Screenshot from 2023-09-01 16-50-49](https://github.com/alelievr/HDRP-Custom-Passes/assets/79392031/da3ac328-79ce-4b2d-87b5-a003a482d428)

I had the same problem using the built-in DrawRenderer custom pass in HDRP when I tried to use it to prevent gun clipping, and when I found this example in this repo and tried it, it has the same problem.
is there a workaround for this?
I'm a noob to rendering and custom passes in HDRP so any help is really appreciated, thanks!

**Comment by alelievr** [comment]
Hey, that should be fixed by this commit: https://github.com/alelievr/HDRP-Custom-Passes/commit/745c44825ca7ebced28df41784f6cd8346d01d73
Though, there are still issues with the SSAO like I mentioned here: https://github.com/alelievr/HDRP-Custom-Passes/issues/44#issuecomment-1861674439 but I don't see who I can fix these without modifying HDRP.
